services:
  - type: web
    name: saivex
    env: python
    buildCommand: pip install -r requirements_production.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SAIVEX_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
