import os
import uuid
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.units import inch

from productivity.research_engine import clean_topic, web_search, make_sections

OUTPUT_DIR = "static/generated"


def create_pdf(title_or_prompt, content=None):
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    topic = clean_topic(title_or_prompt)
    sources = web_search(topic, max_results=10)
    sections = make_sections(topic, sources, count=9)

    filename = f"saivex_research_pdf_{uuid.uuid4().hex[:8]}.pdf"
    path = os.path.join(OUTPUT_DIR, filename)

    doc = SimpleDocTemplate(path, pagesize=A4, rightMargin=46, leftMargin=46, topMargin=48, bottomMargin=42)

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="SaivexTitle", parent=styles["Title"], fontSize=24, textColor=colors.HexColor("#8a5700"), spaceAfter=18))
    styles.add(ParagraphStyle(name="SaivexHeading", parent=styles["Heading1"], fontSize=17, textColor=colors.HexColor("#9b6500"), spaceBefore=14, spaceAfter=8))
    styles.add(ParagraphStyle(name="SaivexBody", parent=styles["BodyText"], fontSize=10.5, leading=15, spaceAfter=8))

    story = []
    story.append(Paragraph(topic.title(), styles["SaivexTitle"]))
    story.append(Paragraph("Research-based report generated by SAIVEX", styles["SaivexBody"]))
    story.append(Spacer(1, 0.18 * inch))

    story.append(Paragraph("Executive Summary", styles["SaivexHeading"]))
    story.append(Paragraph(
        f"This report explains {topic} using a structured research approach. It covers background, concepts, facts, applications, challenges, trends, future scope, and references. Each section focuses on a different angle so the report does not repeat the same content.",
        styles["SaivexBody"]
    ))

    if content:
        story.append(Paragraph("Additional User Requested Content", styles["SaivexHeading"]))
        for para in str(content).split("\n"):
            if para.strip():
                story.append(Paragraph(para.strip(), styles["SaivexBody"]))

    for section in sections:
        story.append(Paragraph(section["title"], styles["SaivexHeading"]))
        for point in section["points"]:
            story.append(Paragraph("• " + point, styles["SaivexBody"]))
        story.append(Spacer(1, 0.08 * inch))

    story.append(PageBreak())
    story.append(Paragraph("Research Sources", styles["SaivexHeading"]))

    data = [["Title", "URL"]]
    for src in sources[:8]:
        data.append([src.get("title", "Source")[:60], src.get("url", "")[:75]])

    table = Table(data, colWidths=[2.5 * inch, 3.7 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#8a5700")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d1b06a")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
    ]))
    story.append(table)

    doc.build(story)
    return path
