import os
import uuid
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor

from productivity.research_engine import clean_topic, web_search, make_sections

OUTPUT_DIR = "static/generated"


def style_slide(slide):
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(10, 5, 1)


def set_title_style(shape, size=34):
    p = shape.text_frame.paragraphs[0]
    p.font.size = Pt(size)
    p.font.bold = True
    p.font.color.rgb = RGBColor(255, 223, 138)


def add_title_slide(prs, topic):
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    style_slide(slide)

    slide.shapes.title.text = topic.title()
    set_title_style(slide.shapes.title, 38)

    subtitle = slide.placeholders[1]
    subtitle.text = "Research-based presentation generated by SAIVEX"
    subtitle.text_frame.paragraphs[0].font.size = Pt(16)
    subtitle.text_frame.paragraphs[0].font.color.rgb = RGBColor(230, 210, 150)


def add_bullets(prs, title, bullets):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    style_slide(slide)

    title_box = slide.shapes.add_textbox(Inches(0.55), Inches(0.35), Inches(9.0), Inches(0.7))
    title_box.text_frame.text = title
    set_title_style(title_box, 27)

    content = slide.shapes.add_textbox(Inches(0.85), Inches(1.25), Inches(8.7), Inches(4.7))
    tf = content.text_frame
    tf.word_wrap = True
    tf.clear()

    for bullet in bullets[:5]:
        p = tf.add_paragraph()
        p.text = bullet
        p.level = 0
        p.font.size = Pt(16)
        p.font.color.rgb = RGBColor(245, 235, 205)

    footer = slide.shapes.add_textbox(Inches(0.55), Inches(6.85), Inches(9.0), Inches(0.3))
    footer.text_frame.text = "SAIVEX Smart Research"
    footer.text_frame.paragraphs[0].font.size = Pt(9)
    footer.text_frame.paragraphs[0].font.color.rgb = RGBColor(185, 150, 80)


def create_ppt(prompt):
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    topic = clean_topic(prompt)
    sources = web_search(topic, max_results=8)
    sections = make_sections(topic, sources, count=9)

    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(7.5)

    add_title_slide(prs, topic)

    add_bullets(prs, "Presentation Roadmap", [
        "Understand the topic from multiple angles",
        "Explore background, facts, applications, and challenges",
        "Connect the topic to current trends and future scope",
        "End with a clear summary and references"
    ])

    for section in sections:
        add_bullets(prs, section["title"], section["points"])

    references = []
    for src in sources[:6]:
        title = src.get("title", "Source")
        url = src.get("url", "")
        references.append(title + (f" — {url}" if url else ""))

    if not references:
        references = ["Research generated using available AI context."]

    add_bullets(prs, "Research Sources", references)

    filename = f"saivex_research_ppt_{uuid.uuid4().hex[:8]}.pptx"
    path = os.path.join(OUTPUT_DIR, filename)
    prs.save(path)
    return path
