import os
import uuid
import zipfile
import random


def clean_prompt(prompt):
    prompt = prompt.replace("create website for", "")
    prompt = prompt.replace("make website for", "")
    prompt = prompt.replace("build website for", "")
    prompt = prompt.replace("generate website for", "")
    return prompt.strip().title()


def create_website(prompt, output_folder="static/generated"):
    os.makedirs(output_folder, exist_ok=True)

    topic = clean_prompt(prompt)

    folder_name = f"saivex_website_{uuid.uuid4().hex[:8]}"
    folder_path = os.path.join(output_folder, folder_name)
    os.makedirs(folder_path, exist_ok=True)

    themes = [
        {
            "bg": "#020617",
            "primary": "#00d4ff",
            "secondary": "#2563eb",
            "card": "#0f172a",
        },
        {
            "bg": "#120701",
            "primary": "#ffbf3c",
            "secondary": "#b66a00",
            "card": "#1f1305",
        },
        {
            "bg": "#07111f",
            "primary": "#22c55e",
            "secondary": "#15803d",
            "card": "#111827",
        },
    ]

    theme = random.choice(themes)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{topic}</title>
<link rel="stylesheet" href="style.css">
</head>
<body>

<nav>
    <h2>{topic}</h2>
    <div>
        <a href="#about">About</a>
        <a href="#features">Features</a>
        <a href="#contact">Contact</a>
    </div>
</nav>

<section class="hero">
    <h1>{topic}</h1>
    <p>A modern responsive website generated by Saivex AI.</p>
    <button onclick="scrollToSection()">Explore More</button>
</section>

<section id="about" class="section">
    <h2>About {topic}</h2>
    <p>
        This website is designed for {topic}. It uses a clean layout,
        modern colors, responsive design, and professional sections.
    </p>
</section>

<section id="features" class="cards">
    <div class="card">
        <h3>Modern Design</h3>
        <p>Clean layout with attractive colors and smooth spacing.</p>
    </div>

    <div class="card">
        <h3>Responsive Layout</h3>
        <p>Works on laptops, tablets, and mobile phones.</p>
    </div>

    <div class="card">
        <h3>Fast Performance</h3>
        <p>Simple HTML, CSS, and JavaScript for fast loading.</p>
    </div>
</section>

<section id="contact" class="section">
    <h2>Contact</h2>
    <p>Use this section to add email, phone number, or social links.</p>
</section>

<footer>
    <p>© 2026 {topic}. Generated by Saivex AI.</p>
</footer>

<script src="script.js"></script>
</body>
</html>"""

    css = f"""* {{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: Arial, sans-serif;
}}

body {{
    background: {theme["bg"]};
    color: white;
}}

nav {{
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 24px 8%;
    background: rgba(255,255,255,0.04);
    border-bottom: 1px solid rgba(255,255,255,0.1);
}}

nav h2 {{
    color: {theme["primary"]};
}}

nav a {{
    color: white;
    text-decoration: none;
    margin-left: 20px;
}}

.hero {{
    min-height: 75vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    padding: 0 8%;
    background: linear-gradient(135deg, {theme["secondary"]}, {theme["bg"]});
}}

.hero h1 {{
    font-size: 58px;
    margin-bottom: 18px;
}}

.hero p {{
    font-size: 20px;
    max-width: 650px;
    margin-bottom: 28px;
}}

button {{
    width: fit-content;
    padding: 14px 28px;
    border: none;
    border-radius: 30px;
    background: {theme["primary"]};
    color: #000;
    font-weight: bold;
    cursor: pointer;
}}

.section {{
    padding: 70px 8%;
}}

.section h2 {{
    font-size: 36px;
    margin-bottom: 16px;
    color: {theme["primary"]};
}}

.section p {{
    max-width: 800px;
    line-height: 1.7;
    color: #d1d5db;
}}

.cards {{
    padding: 70px 8%;
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(230px, 1fr));
    gap: 24px;
}}

.card {{
    background: {theme["card"]};
    padding: 28px;
    border-radius: 22px;
    border: 1px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 30px rgba(0,0,0,0.25);
}}

.card h3 {{
    margin-bottom: 12px;
    color: {theme["primary"]};
}}

.card p {{
    color: #d1d5db;
    line-height: 1.6;
}}

footer {{
    text-align: center;
    padding: 28px;
    background: rgba(0,0,0,0.35);
    color: #d1d5db;
}}

@media(max-width: 700px) {{
    nav {{
        flex-direction: column;
        gap: 14px;
    }}

    nav a {{
        margin: 0 8px;
    }}

    .hero h1 {{
        font-size: 38px;
    }}

    .hero p {{
        font-size: 16px;
    }}
}}
"""

    js = """function scrollToSection(){
    document.getElementById("about").scrollIntoView({
        behavior: "smooth"
    });
}
"""

    with open(os.path.join(folder_path, "index.html"), "w", encoding="utf-8") as file:
        file.write(html)

    with open(os.path.join(folder_path, "style.css"), "w", encoding="utf-8") as file:
        file.write(css)

    with open(os.path.join(folder_path, "script.js"), "w", encoding="utf-8") as file:
        file.write(js)

    zip_filename = f"{folder_name}.zip"
    zip_path = os.path.join(output_folder, zip_filename)

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zip_file:
        zip_file.write(os.path.join(folder_path, "index.html"), arcname="index.html")
        zip_file.write(os.path.join(folder_path, "style.css"), arcname="style.css")
        zip_file.write(os.path.join(folder_path, "script.js"), arcname="script.js")

    preview_url = f"/static/generated/{folder_name}/index.html"
    download_url = f"/static/generated/{zip_filename}"

    return preview_url, download_url