import os
import uuid
import zipfile
from pathlib import Path

from productivity.research_engine import clean_topic, web_search, make_sections

OUTPUT_DIR = "static/generated"


def create_website(prompt):
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    topic = clean_topic(prompt)
    sources = web_search(topic, max_results=8)
    sections = make_sections(topic, sources, count=8)

    site_id = uuid.uuid4().hex[:8]
    folder_name = f"saivex_website_{site_id}"
    folder = Path(OUTPUT_DIR) / folder_name
    folder.mkdir(parents=True, exist_ok=True)

    nav = "".join([f'<a href="#sec{i}">{s["title"]}</a>' for i, s in enumerate(sections[:7])])

    cards = ""
    for i, section in enumerate(sections[:7]):
        points = "".join([f"<li>{p}</li>" for p in section["points"][:4]])
        cards += f"""
        <section class="section reveal" id="sec{i}">
            <div class="section-label">0{i+1}</div>
            <h2>{section['title']}</h2>
            <ul>{points}</ul>
        </section>
        """

    source_cards = ""
    for src in sources[:6]:
        title = src.get("title", "Source")
        url = src.get("url", "#")
        snippet = src.get("snippet", "")
        source_cards += f"""
        <div class="source-card">
            <h3>{title}</h3>
            <p>{snippet[:180]}</p>
            <a href="{url}" target="_blank">Open Source</a>
        </div>
        """

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{topic.title()}</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<header class="hero">
    <nav>
        <div class="brand">SAIVEX</div>
        <div class="links">{nav}</div>
    </nav>
    <div class="hero-content">
        <div class="badge">Research Website</div>
        <h1>{topic.title()}</h1>
        <p>A modern, research-based website generated by SAIVEX using structured sections and varied information.</p>
        <a class="cta" href="#sec0">Explore Topic</a>
    </div>
</header>

<main>
    {cards}

    <section class="sources reveal">
        <h2>Research Sources</h2>
        <div class="source-grid">
            {source_cards}
        </div>
    </section>
</main>

<footer>
    Generated by SAIVEX Smart Website Generator
</footer>

<script src="script.js"></script>
</body>
</html>"""

    css = """*{box-sizing:border-box;margin:0;padding:0}
body{font-family:Arial,sans-serif;background:#080300;color:#fff7d6;line-height:1.6}
.hero{min-height:100vh;background:radial-gradient(circle at top,#4a2b05,#080300 60%),linear-gradient(135deg,#100701,#061324);padding:24px}
nav{display:flex;justify-content:space-between;align-items:center;gap:20px;position:sticky;top:0;background:rgba(0,0,0,.35);backdrop-filter:blur(16px);border:1px solid rgba(255,196,77,.2);border-radius:18px;padding:14px 20px}
.brand{font-weight:900;letter-spacing:4px;color:#ffdf8a;font-size:22px}
.links{display:flex;gap:12px;flex-wrap:wrap}
.links a{color:#fff2bf;text-decoration:none;font-size:14px}
.hero-content{max-width:900px;margin:18vh auto 0;text-align:center}
.badge{display:inline-block;border:1px solid rgba(255,196,77,.3);padding:8px 14px;border-radius:999px;color:#ffdf8a;margin-bottom:18px}
h1{font-size:clamp(42px,8vw,90px);color:#fff0b1;text-shadow:0 0 30px rgba(255,191,60,.45)}
.hero p{font-size:20px;color:#e7d4a2;max-width:740px;margin:18px auto}
.cta{display:inline-block;margin-top:22px;background:linear-gradient(90deg,#ffbf3c,#b66a00);color:#1b0c00;text-decoration:none;font-weight:900;padding:14px 22px;border-radius:16px}
main{padding:40px 7vw}
.section{position:relative;margin:28px auto;padding:34px;border:1px solid rgba(255,196,77,.22);background:rgba(255,255,255,.06);backdrop-filter:blur(18px);border-radius:28px;max-width:1100px;box-shadow:0 20px 50px rgba(0,0,0,.25)}
.section-label{color:#ffbf3c;font-weight:900;letter-spacing:3px}
h2{font-size:34px;margin:8px 0 18px;color:#ffdf8a}
li{margin:10px 0;color:#fff5d3}
.sources{max-width:1100px;margin:55px auto}
.source-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:18px}
.source-card{border:1px solid rgba(255,196,77,.22);border-radius:20px;padding:20px;background:rgba(255,255,255,.055)}
.source-card h3{color:#ffdf8a;margin-bottom:10px}
.source-card p{color:#d8c99b;font-size:14px}
.source-card a{display:inline-block;margin-top:12px;color:#00d4ff}
footer{text-align:center;padding:30px;color:#d6c08a;border-top:1px solid rgba(255,196,77,.15)}
.reveal{opacity:0;transform:translateY(25px);transition:.7s ease}
.reveal.show{opacity:1;transform:none}
@media(max-width:760px){nav{align-items:flex-start;flex-direction:column}.links{display:none}.hero-content{margin-top:14vh}main{padding:25px 14px}.section{padding:24px}h2{font-size:27px}}"""

    js = """const items = document.querySelectorAll(".reveal");
const observer = new IntersectionObserver(entries=>{
  entries.forEach(entry=>{
    if(entry.isIntersecting){ entry.target.classList.add("show"); }
  });
},{threshold:.15});
items.forEach(item=>observer.observe(item));"""

    (folder / "index.html").write_text(html, encoding="utf-8")
    (folder / "style.css").write_text(css, encoding="utf-8")
    (folder / "script.js").write_text(js, encoding="utf-8")

    zip_path = Path(OUTPUT_DIR) / f"{folder_name}.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for file in folder.rglob("*"):
            z.write(file, arcname=str(file.relative_to(folder)))

    preview_url = "/" + str(folder / "index.html").replace("\\", "/")
    download_url = "/" + str(zip_path).replace("\\", "/")
    return preview_url, download_url
